version: "3.8"

volumes:
  suproc_data:

services:

  mongo:
    container_name: suproc_mongo
    image: mongo:bionic
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - suproc_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - backend
    ports:
      - 27017:27017

  server:
    container_name: suproc_server
    build:
      context: ./packages/server
      dockerfile: Dockerfile-dev
    volumes:
      - ./packages/server:/usr/app
    depends_on:
      - "mongo"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      mailerUser: "${MAILER_USER}"
      mailerPassword: "${MAILER_PASSWORD}"
    networks:
      - backend
      - web
    ports:
      - 8080:8080

  ui:
    container_name: suproc_ui
    build:
      context: ./packages/ui
      dockerfile: Dockerfile-dev
    volumes:
      - ./packages/ui:/usr/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web
    ports:
      - 3000:3000

  gateway:
    container_name: suproc_gateway
    image: nginx
    networks:
      - web
    ports:
      - 443:443
    volumes:
      - ./gateway/development/conf.d:/etc/nginx/conf.d
    depends_on:
      - server
      - ui

networks:
  web: {}
  backend: {}
